name: Bump version

on:
  push:
    branches:
      - main

jobs:
  release-please:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple